name: Build and deploy .NET application to container app media-voyager
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  CONTAINER_APP_NAME: media-voyager
  CONTAINER_APP_RESOURCE_GROUP_NAME: ContainerAppResourceGrp
  DOTNET_CORE_VERSION: 9.0.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-quality: preview
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      - name: Build and test
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet test --no-build --configuration Release
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MEDIAVOYAGER_AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.MEDIAVOYAGER_AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.MEDIAVOYAGER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MEDIAVOYAGER_AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to Container Apps using source-based deployment
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }}
      - name: logout
        run: az logout
